### ISSUE TITLE
Не безопасный пароль

### ISSUE THREAD

**Issue by UksusoFF** [ulogin/ulogin-MediaWiki#6]
В расширении используется пароль состоящий из хешированого ника ($u->setPassword(md5($username . $uLoginUser['email']));).
Не очень то безопасно это.
В старой версии хорошо бы это заменить на: User::randomPassword().
В новой 1.27 на: PasswordFactory::generateRandomPasswordString().

Новую можно смерджить отсюда: https://github.com/UksusoFF/ulogin-MediaWiki/commit/e604c85782a073d3dbff0a41adb4445cada96c84

**Comment by ulogin-team** [comment]
Спасибо за замечание! 
Для старых версий внесли исправление. Для новой 1.27 вы сами порешали, спасибо )
